### PR TITLE
Remove yarn tsc command

### PR DESCRIPTION
**Pull request by liywjl**
## What does this change?
- remove `yarn tsc` command
- `pre-push` uses `yarn build` instead of `yarn tsc`

## Why?
- We want to check that the build works, we should use our command to do that check instead of `yarn tsc` 
- When running `yarn tsc` without options, we would compile `xx.test.tsx` files as well, that in turn would be picked up by Jest

### CODE REVIEW

**Comment by oliverlloyd** [comment]
How can I run `yarn tsc` locally to check I don't have typescript errors?

**Comment by oliverlloyd** [comment]
All the other repos have `yarn tsc` as the standard way to check for issues - I don't think we should diverge from that in discussion. Is there another way to do what you need here?

**Comment by liywjl** [comment]
> How can I run `yarn tsc` locally to check I don't have typescript errors?

you can run `yarn createTsDec`

**Comment by liywjl** [comment]
> All the other repos have `yarn tsc` as the standard way to check for issues - I don't think we should diverge from that in discussion. Is there another way to do what you need here?

You are right, I think maybe I should just remove `createTsDec`, reinstate `yarn tsc`, put the confligs into `tsconfig` and we can they just use that?

**Comment by liywjl** [comment]
closing in favor of https://github.com/guardian/discussion-rendering/pull/459

**Pull request closed without merging**
